GET http://localhost:8080/tasks


###

POST http://localhost:8080/tasks
content-type: application/json

{
    "title": "New Task",
    "description": "A new Task",
    "status": "ongoing"
}


###

GET http://localhost:8080/tasks/fff570be-0308-4d62-8078-300ff26b4d01


###
PUT http://localhost:8080/tasks/e7eea028-1906-4f75-b854-4cc9f12e8900
content-type: application/json

{
    "title": "Updated New Task",
    "description": "A new Task",
    "status": "done"
}

###

DELETE http://localhost:8080/tasks/925863ba-7d41-4897-8411-f35f28983fc5


###

POST http://localhost:8080/hello